In [1]:
import numpy as np
import pandas as pd
0np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

In [2]:
mylist = [1,2,3]

In [3]:
np.ones((10, 5)).shape

(10, 5)

In [4]:
np.ones((3, 4, 5), dtype=np.float64).strides


(160, 40, 8)

In [5]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.ones((3, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [7]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)


True

In [8]:
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [9]:
mylist = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [13]:

np.ones((3,10,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
floats

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [15]:
np.issubdtype(floats.dtype, np.floating)

True

In [16]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [17]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [19]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
arr.reshape((5, -1))[-1]

array([24, 25, 26, 27, 28, 29])

In [31]:
for x in range(0,5):
    print(x)

0
1
2
3
4


In [26]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [37]:
[[0, 1], [2, 3], [4,5]]

[[0, 1], [2, 3], [4, 5]]

In [44]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [45]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [46]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arr = np.random.randn(6)

arr

array([ 1.669 , -0.4386, -0.5397,  0.477 ,  3.2489, -1.0212])

In [51]:
arr.sort()

In [52]:
arr

array([-1.0212, -0.5397, -0.4386,  0.477 ,  1.669 ,  3.2489])

In [54]:
arr = np.random.randn(3, 5)
arr


array([[ 0.3329, -2.3594, -0.1995, -1.542 , -0.9707],
       [-1.307 ,  0.2863,  0.378 , -0.7539,  0.3313],
       [ 1.3497,  0.0699,  0.2467, -0.0119,  1.0048]])

In [55]:
arr[:, 0].sort()  # Sort first column values in-place
arr

array([[-1.307 , -2.3594, -0.1995, -1.542 , -0.9707],
       [ 0.3329,  0.2863,  0.378 , -0.7539,  0.3313],
       [ 1.3497,  0.0699,  0.2467, -0.0119,  1.0048]])

In [58]:
arr[:, 1]

array([-2.3594,  0.2863,  0.0699])

In [60]:
arr[:, 4]

array([-0.9707,  0.3313,  1.0048])

In [61]:
import numpy as np
data = {i : np.random.randn() for i in range(7)}
data

{0: 1.327194613785634,
 1: -0.9192615577450494,
 2: -1.5491064382844495,
 3: 0.0221845986581725,
 4: 0.7583631450155793,
 5: -0.6605243277245674,
 6: 0.862580082530047}

In [62]:
type(data)

dict

In [71]:
x= []
for i in range(7):
#     print (i)
    x.append(i)
    
x

0
1
2
3
4
5
6


[0, 1, 2, 3, 4, 5, 6]

In [77]:
y = [i%2 for i in range(7)]

In [78]:
y

[0, 1, 0, 1, 0, 1, 0]

In [82]:
divided = [x for x in range(100)  if x % 7 == 0]

print(divided)

[0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


In [80]:
[x for x in range(100)]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [85]:
def f(x, y, z):
    return (x + y) / z

a = 3
b = 6
c = 3

result = f(a, b, c)

In [86]:
result

3.0

In [91]:
x = 5
y = 7
if x > 3:
    x += 1
    y = 8


In [92]:
y

8

In [93]:
x

6

In [94]:
a = 'foo'

getattr(a, 'split')


<function str.split>

In [97]:
a.split()

['foo']

In [101]:
a.capitalize().capitalize()

'Foo'

In [99]:
a.islower()

True

In [100]:
a

'foo'

In [102]:
 a.upper()

'FOO'

In [103]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError: # not iterable
        return False

In [106]:
a=[10,2]

In [107]:
for x in a:
    print(x)

10
2


In [108]:
x=10


In [109]:
isiterable('a string')


True

In [110]:
for x in 'a string':
    print(x)

a
 
s
t
r
i
n
g


In [111]:
isiterable([1, 2, 3])


True

In [112]:
isiterable(5)

False

In [122]:
a = [1, 2, 3]
b = a
c = list(a)



In [123]:
a

[1, 2, 3]

In [124]:
c

[1, 2, 3]

In [115]:
a is b
a is not c

True

In [125]:
a == c


True

In [116]:
a.append(4)

In [126]:

a_list = ['foo', 2, [4, 5]]
a_list[2] = (3, 4)
a_list

['foo', 2, (3, 4)]

In [127]:

a_tuple = (3, 5, (4, 5))
a_tuple[1] = 'four'

TypeError: 'tuple' object does not support item assignment

In [117]:
a

[1, 2, 3, 4]

In [118]:
b

[1, 2, 3, 4]

In [119]:
c

[1, 2, 3]

In [120]:
a is b

True

In [121]:
a is c

False

In [128]:

3 / 2

1.5

In [129]:

3 // 2

1

In [131]:
10/3

3.3333333333333335

In [132]:
10%3

1

In [133]:
10//3

3